name: kivu-ctd
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.23.5
  - pandas==1.5.3 # <2.0 to use xarray 2022.11.0 
  - scipy=1.9.3
  - matplotlib=3.10.8
  - netcdf4=1.7.4
  - xarray=2022.11.0 # More recent versions can't be used with cmocean 3.0.3
  - openpyxl=3.1.5
  - pyyaml=6.0.3
  - dateparser=1.2.0
  - python-dateutil=2.9.0.post0
  - gsw=3.6.19
  - notebook=7.2.2
  - ipympl=0.9.7
  - pip
  - pip:
    - envass==1.0.0 
    - cmocean==3.0.3 
    - numpy==1.23.5 # Required to avoid pip to upgrade
    - scipy==1.9.3 # Required to avoid pip to upgrade

